# Generated by Django 2.1.8 on 2019-08-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_explain',
            field=models.TextField(),
        ),
    ]
